apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitor-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/status
        pathType: Prefix
        backend:
          service:
            name: monitor-backend-service
            port:
              number: 8000
